"""add status into rewards table

Revision ID: 144d122034ae
Revises: fbe084502cd6
Create Date: 2026-04-21 13:33:13.393699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144d122034ae'
down_revision: Union[str, Sequence[str], None] = 'fbe084502cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewards', sa.Column('status', sa.String(length=20), server_default='available', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rewards', 'status')
    # ### end Alembic commands ###
