"""add scoring_snapshot_json to task_instances

Revision ID: 262d2a29711f
Revises: 9b53f537ff01
Create Date: 2026-03-22 10:53:54.227438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '262d2a29711f'
down_revision: Union[str, Sequence[str], None] = '9b53f537ff01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_instances', sa.Column('scoring_snapshot_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_instances', 'scoring_snapshot_json')
    # ### end Alembic commands ###
