"""add deleted_at columns

Revision ID: 2c0f0576cb08
Revises: 897c4119ff5a
Create Date: 2026-05-18 09:10:48.333442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0f0576cb08'
down_revision: Union[str, Sequence[str], None] = '897c4119ff5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('task_instances_task_schedule_id_fkey'), 'task_instances', type_='foreignkey')
    op.create_foreign_key(None, 'task_instances', 'task_schedules', ['task_schedule_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_instances', type_='foreignkey')
    op.create_foreign_key(op.f('task_instances_task_schedule_id_fkey'), 'task_instances', 'task_schedules', ['task_schedule_id'], ['id'])
    # ### end Alembic commands ###
