"""create redemptions table

Revision ID: 395e4081eb5a
Revises: b5c79b619de9
Create Date: 2026-04-07 02:24:03.776757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395e4081eb5a'
down_revision: Union[str, Sequence[str], None] = 'b5c79b619de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redemptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=False),
    sa.Column('reward_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('point_spent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redemptions_id'), 'redemptions', ['id'], unique=True)
    op.create_index(op.f('ix_redemptions_reward_id'), 'redemptions', ['reward_id'], unique=False)
    op.create_index(op.f('ix_redemptions_user_id'), 'redemptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redemptions_user_id'), table_name='redemptions')
    op.drop_index(op.f('ix_redemptions_reward_id'), table_name='redemptions')
    op.drop_index(op.f('ix_redemptions_id'), table_name='redemptions')
    op.drop_table('redemptions')
    # ### end Alembic commands ###
