"""create point ledger table

Revision ID: 4e77fd45d233
Revises: 313c926b5af2
Create Date: 2026-03-27 10:36:41.577419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e77fd45d233'
down_revision: Union[str, Sequence[str], None] = '313c926b5af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_ledgers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_ledgers_entry_type'), 'point_ledgers', ['entry_type'], unique=False)
    op.create_index(op.f('ix_point_ledgers_id'), 'point_ledgers', ['id'], unique=True)
    op.create_index(op.f('ix_point_ledgers_source_id'), 'point_ledgers', ['source_id'], unique=False)
    op.create_index(op.f('ix_point_ledgers_source_type'), 'point_ledgers', ['source_type'], unique=False)
    op.create_index(op.f('ix_point_ledgers_user_id'), 'point_ledgers', ['user_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'scoring_schemes', ['scoring_scheme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_point_ledgers_user_id'), table_name='point_ledgers')
    op.drop_index(op.f('ix_point_ledgers_source_type'), table_name='point_ledgers')
    op.drop_index(op.f('ix_point_ledgers_source_id'), table_name='point_ledgers')
    op.drop_index(op.f('ix_point_ledgers_id'), table_name='point_ledgers')
    op.drop_index(op.f('ix_point_ledgers_entry_type'), table_name='point_ledgers')
    op.drop_table('point_ledgers')
    # ### end Alembic commands ###
