"""add deleted_at columns

Revision ID: 897c4119ff5a
Revises: 144d122034ae
Create Date: 2026-05-18 09:04:02.019583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897c4119ff5a'
down_revision: Union[str, Sequence[str], None] = '144d122034ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('point_ledgers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('redemptions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rewards', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('rewards', 'deleted_at')
    op.drop_column('redemptions', 'deleted_at')
    op.drop_column('point_ledgers', 'deleted_at')
    op.drop_column('goals', 'deleted_at')
    # ### end Alembic commands ###
