"""create task instance table

Revision ID: 9b53f537ff01
Revises: 9bfbb0fbb950
Create Date: 2026-03-22 10:20:33.146328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b53f537ff01'
down_revision: Union[str, Sequence[str], None] = '9bfbb0fbb950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_schedule_id', sa.Integer(), nullable=False),
    sa.Column('date_instance', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='todo', nullable=False),
    sa.Column('completion_level', sa.String(length=200), nullable=True),
    sa.Column('score_awarded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('generated_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_schedule_id'], ['task_schedules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_instances_id'), 'task_instances', ['id'], unique=True)
    op.create_index(op.f('ix_task_instances_task_id'), 'task_instances', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_instances_task_schedule_id'), 'task_instances', ['task_schedule_id'], unique=False)
    op.create_index(op.f('ix_task_instances_user_id'), 'task_instances', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_instances_user_id'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_task_schedule_id'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_task_id'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_id'), table_name='task_instances')
    op.drop_table('task_instances')
    # ### end Alembic commands ###
