"""create task_schedules table

Revision ID: 9bfbb0fbb950
Revises: 7b188534a8d4
Create Date: 2026-03-19 13:26:12.004945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bfbb0fbb950'
down_revision: Union[str, Sequence[str], None] = '7b188534a8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('schedule_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'ONCE', name='schedule_type_enum'), nullable=False),
    sa.Column('schedule_value_json', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_schedules_id'), 'task_schedules', ['id'], unique=True)
    op.create_index(op.f('ix_task_schedules_task_id'), 'task_schedules', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_schedules_user_id'), 'task_schedules', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_schedules_user_id'), table_name='task_schedules')
    op.drop_index(op.f('ix_task_schedules_task_id'), table_name='task_schedules')
    op.drop_index(op.f('ix_task_schedules_id'), table_name='task_schedules')
    op.drop_table('task_schedules')
    # ### end Alembic commands ###
