"""create scoring schemes table

Revision ID: b26a4af196a7
Revises: 262d2a29711f
Create Date: 2026-03-26 09:40:36.575176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26a4af196a7'
down_revision: Union[str, Sequence[str], None] = '262d2a29711f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_schemes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('levels_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_schemes_id'), 'scoring_schemes', ['id'], unique=True)
    op.create_index(op.f('ix_scoring_schemes_user_id'), 'scoring_schemes', ['user_id'], unique=False)
    op.alter_column(
    'tasks',
    'scoring_scheme_id',
    type_=sa.Integer(),
    postgresql_using='scoring_scheme_id::integer'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'scoring_scheme_id',
               existing_type=sa.Integer(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_scoring_schemes_user_id'), table_name='scoring_schemes')
    op.drop_index(op.f('ix_scoring_schemes_id'), table_name='scoring_schemes')
    op.drop_table('scoring_schemes')
    # ### end Alembic commands ###
