"""change point spent name to cost point

Revision ID: fbe084502cd6
Revises: 395e4081eb5a
Create Date: 2026-04-07 08:11:45.707263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe084502cd6'
down_revision: Union[str, Sequence[str], None] = '395e4081eb5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "redemptions",
        "point_spent",
        new_column_name="cost_points"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "redemptions",
        "cost_points",
        new_column_name="point_spent"
    )
    # ### end Alembic commands ###
